'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4971
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("iROB_EA_V1_Consola.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _error() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_error", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property application() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("application", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ArduinoLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ArduinoLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bateria_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bateria_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property calendar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property chart() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("chart", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property comment() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("comment", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property contact() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("contact", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property download() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property edit() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("edit", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property fondo_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_colorpicker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_colorpicker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_equalizer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_equalizer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_flash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_flash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_halt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_halt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_light_azul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_light_azul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_light_blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_light_blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_light_rojo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_light_rojo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_onoff_rojo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_onoff_rojo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_signal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_signal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_smalltiles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_smalltiles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ic_menu_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_menu_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property log_out() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("log_out", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property portfolio() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("portfolio", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ROB_EA_logo_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROB_EA_logo_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ROB_EA_logo_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROB_EA_logo_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ROB_EA_Version_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROB_EA_Version_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ROB_EA_Version_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROB_EA_Version_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rss() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("rss", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("search2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property security() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("security", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property service() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("service", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property shopping_cart() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shopping_cart", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property user_female() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user_female", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property user_male() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("user_male", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property volcado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("volcado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
